defaultIndent: "  "

noIndentBlock:
  noindent: 1

modifyLineBreaks:
  items:
    ItemStartsOnOwnLine: 1
    ItemFinishesWithLineBreak: 1
  environments:
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
    DBSFinishesWithLineBreak: 1
